Updated the logic for the new website and updated the CRON time for github actions

diff --git a/.github/workflows/book_football.yml b/.github/workflows/book_football.yml
--- a/.github/workflows/book_football.yml
+++ b/.github/workflows/book_football.yml
@@ -2,7 +2,8 @@ name: Weekly Football Field Booking
 
 on:
   schedule:
-    - cron: '40 17 * * 4'  # Every Tuesday at 19:50 EEST (which is 16:50 UTC)
+    - cron: '50 16 * * 2'  # Every Tuesday at 19:50 EEST (summer) (which is 16:50 UTC)
+    - cron: '50 17 * * 2'  # Every Tuesday at 19:50 EET (winter) (which is 17:50 UTC)
   workflow_dispatch:  # Optional: allows manual triggering
 
 jobs:
@@ -22,7 +23,7 @@ jobs:
       - name: Install Playwright and dependencies
         run: |
           pip install playwright
-          playwright install chromium
+          playwright install --with-deps chromium
 
       - name: Run booking script
         env:
@@ -30,4 +31,4 @@ jobs:
           BOOKING_PASSWORD: ${{ secrets.BOOKING_PASSWORD }}
           BOOKING_URL: ${{ vars.BOOKING_URL_FOOTBALL }}
           BOOKING_DAY_OF_WEEK: ${{ vars.BOOKING_DAY_FOOTBALL }}
-        run: python -u football_script.py
+        run: python -u football_script.py || echo "Script failed"
